Create Login Component
codeforcauseorg/causefolio pull request #16
Opened 2021-02-24 05:13 UTC by mdPial

### Description

I have created a Login component. Let me know if have anything to fix.  :smiley: 
### Related Issue

Fixes #7   [Frontend] Create Login component

### Type of Change:

- Code
- User Interface

### Checklist:

- [x] Pull request is made against `development` branch.
- [x] My code follows the style guidelines of this project.
- [x] I run `npm run format` before creating the pull request.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings

- [x] UI made replicates the design provided

2021-02-26 13:12 UTC, Abhishek-kumar09 commented
@mdPial Have you linked the component somewhere, I mean I could only see the Login Component file, and no changes in any other file where it could be linked or called from.

You can read about how to show your content in popup and dialogs here: https://material-ui.com/components/dialogs/

2021-02-26 13:20 UTC, mdPial commented
@Abhishek-kumar09 No I have not linked in my PR. In the issue I asked about it and got answer to just create the component for now.

2021-02-26 13:30 UTC, Abhishek-kumar09 commented
Okay, okay no problem. Unless you don't link it to some existing components or create separate route How can I view your changes.

Sorry the comment was bit misleading.

If you are getting some problem in linking and how to show components you can ping me anytime

2021-02-26 14:01 UTC, mdPial commented
It's okay. I was also thinking the same thing how will you see the changes then thought might be there is a cool way to do that😁😁

2021-02-27 14:49 UTC, mdPial commented
I am having issue on this
![image](https://user-images.githubusercontent.com/43095489/109390546-80277400-793c-11eb-9a7c-19f30844bebf.png)
I couldn't modify default dialog border `radius` and custom `width and height` in **px**. Could you help me on this?

2021-02-27 15:47 UTC, Abhishek-kumar09 commented
Push the code and will see

2021-02-28 02:19 UTC, mdPial commented
I have updated last time I had forgotten to add separate closing option :sweat_smile:

2021-02-28 03:21 UTC, mdPial commented
I don't know why checks are not successful. It's running without any problem in my localhost.

2021-02-28 10:12 UTC, Abhishek-kumar09 commented
![image](https://user-images.githubusercontent.com/48255244/109414884-8b7dac80-79db-11eb-85f2-1d5ccf433939.png)
No unused variables should be there. image should have an alt prop.

> I don't know why checks are not successful. It's running without any problem in my localhost.

2021-02-28 13:09 UTC, mdPial commented
Updated. Is there any way to check those locally?

2021-03-02 09:54 UTC, Abhishek-kumar09 commented
Ya this errors also popup in the console

2021-03-02 10:23 UTC, Abhishek-kumar09 requested changes
Some minors

2021-03-02 10:23 UTC, Abhishek-kumar09 commented on src/components/Login.js
> +        <input className={classes.input} variant="outlined" />
```diff
-        <input className={classes.input} variant="outlined" />
-        <Typography>Password</Typography>
-        <input className={classes.input} variant="outlined" />
+        <input className={classes.input} type="email" variant="outlined" />
+        <Typography>Password</Typography>
+        <input className={classes.input} type="password" variant="outlined" />
```

2021-03-02 10:23 UTC, Abhishek-kumar09 commented on src/layouts/MainLayout/TopBar/Account.js
>    button: {
To fixup the border-radius thing:

add one more class:
```
  dialog: {
    '& .MuiDialog-paper': {
      borderRadius: '20px'
    }
  }
```

and put that class here :
```diff
        <Dialog
          maxWidth
          open={!user && !!loginFlag}
          onClose={handleClose}
          aria-labelledby="form-dialog-title"
+          className={classes.dialog}
        >
          <Login handleClose={handleClose} />
        </Dialog>
```

2021-03-02 13:55 UTC, Abhishek-kumar09 requested changes
Changes are superawesome for desktop, On mobile:
![image](https://user-images.githubusercontent.com/48255244/109658780-f9b5a100-7b8c-11eb-86c3-f8ad535dde0b.png)

Put the image taking whole width(xs={12})
then put the login components inputs and buttons

2021-03-03 15:07 UTC, mdPial commented
I am facing difficulty to make Card responsive. Could you guide me by resources?

2021-03-04 07:54 UTC, mdPial commented
I have updated

2021-03-04 08:27 UTC, merged

2021-03-04 08:27 UTC, Abhishek-kumar09 commented
Thanks @mdPial Loved it!

2021-03-04 08:29 UTC, Abhishek-kumar09 commented
You can add yourself in contributor list in a new PR, and could start grabbing other issues

2021-03-04 11:47 UTC, mdPial commented
It's my pleasure @Abhishek-kumar09 . Thank you for helping.