Created stats component
codeforcauseorg/causefolio pull request #30
Opened 2021-03-04 14:16 UTC by AdityaTeltia

### Description

Designed and created stats component inside ```src/components``` with the name ```Stats.js```.

### Related Issue

Fixes #24 

### Type of Change:

- Code
- User Interface
- New Feature

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

Tested by rendering the component in local machine.

### Checklist:

- [x] Pull request is made against `development` branch.
- [x] My code follows the style guidelines of this project.
- [x] I run `npm run format` before creating the pull request.
- [x] I have performed a self-review of my own code.

### Screenshots (if appropriate):
![stats](https://user-images.githubusercontent.com/67232537/109976808-2fd85980-7d22-11eb-8d9e-6a021f3e49cd.JPG)

2021-03-09 15:05 UTC, Abhishek-kumar09 commented
@AdityaTeltia Can you provide the full page screenshot

2021-03-09 15:16 UTC, AdityaTeltia commented
> @AdityaTeltia Can you provide the full page screenshot

![localhost_3000_ (2)](https://user-images.githubusercontent.com/67232537/110492777-7cec6f00-8118-11eb-91c5-27883d02a94b.png)

2021-03-09 15:19 UTC, AdityaTeltia commented
We just have to add this component in ```Navigation.js``` component that I merged earlier in #21 and We will get this , Also I don't think issue #22 needs to be there anymore as I have pushed the` header` component along with `Navigation` one.
@Abhishek-kumar09

2021-03-09 16:27 UTC, Abhishek-kumar09 commented
> We just have to add this component in Navigation.js

Have you done it? If not please do.

2021-03-09 16:42 UTC, AdityaTeltia commented
> > We just have to add this component in Navigation.js
> 
> Have you done it? If not please do.

Actually , In my `temp2` branch the `navigation` component is not present as I was working parallely on two issues and the `navigation` component got merged.
So should I create a new PR with a new branch or there are any commands so that I can even my `temp2` branch with `origin`

2021-03-09 16:49 UTC, Abhishek-kumar09 commented
you can do:
```
git merge navigation
```
It may help.

2021-03-10 13:53 UTC, Abhishek-kumar09 requested changes

2021-03-10 13:53 UTC, Abhishek-kumar09 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +1. 2. 3.
Please revert this.

2021-03-10 14:23 UTC, merged